#!/usr/bin/env python3
"""Copy the DarkMode UI pieces and relic spin icons the survivors UI uses into the repo.

Sources are the purchased packs in ~/Downloads. The licenses allow shipping the art inside
the game but not redistributing the packs, so only the used crops are copied.
"""
from pathlib import Path
from PIL import Image

HOME = Path.home() / 'Downloads'
PIX = HOME / 'Pixelarium - Interfaces Bundle - Full version/Pack Content'
DARK = PIX / 'DarkMode Interface'
ZELDA = PIX / 'Zelda-Like Interface'
TINY = HOME / 'Tiny Dungeons - Items Pack/Tiny Dungeons - Items Pack/items/procedural_animations'
ROOT = Path(__file__).resolve().parent.parent
NINJA = ROOT / 'assets/Ninja Adventure - Asset Pack/Items'
import json
VFXMIX = HOME / 'FullBundle/AllPackBundle/VfxMix'
FX_OUT = ROOT / 'assets/fx/vfxmix'
SHEETS = ROOT / 'assets/fx/sheets'
# Sheets the juice uses, read from the artist's JSON so re-exports need no code change.
FX_FROM_JSON = ['Capture_Ring', 'Capture_Fill', 'Capture_Burst', 'Reward_Trail', 'Slot_PowerUp',
    'LevelUp_Aura_Ignite_Back', 'LevelUp_Aura_Ignite_Front', 'LevelUp_Aura_Loop_Back', 'LevelUp_Aura_Loop_Front',
    'LevelUp_Aura_Fade_Back', 'LevelUp_Aura_Fade_Front', 'Unlock_Rays', 'Unlock_Fill']
# Sheets without artist JSON: src, frame w/h, frames, fps, loop, anchor x/y.
FX_EXTRA = {
    'ShrineStates': ('assets/fx/ShrineStates.png', 32, 32, 4, 1, False, 16, 31),
    'Spark_Light': ('assets/fx/vfxmix/spark_04.png', 142, 119, 16, 24, False, 71, 60),
    'P_Shard': ('assets/fx/vfxmix/gem_broken_yellow.png', 18, 16, 6, 1, False, 9, 8),
    'P_Rock': ('assets/fx/vfxmix/rock_gray.png', 22, 22, 6, 1, False, 11, 11),
}
UI_OUT = ROOT / 'assets/ui/darkmode'
ICON_OUT = ROOT / 'assets/icons/relics'

CROPS = {  # output name: (source, crop box or None)
    'panel': (DARK / 'Dialogue interfaces/spr_dialogue_box_withoutstartingpoint_9slice.png', (5, 5, 37, 37)),
    'slot': (DARK / 'Player interface/Player Status/spr_item_slot.png', None),
    'pill': (DARK / 'Dialogue interfaces/spr_dialogue_box_button.png', (1, 1, 21, 12)),
    'banner': (DARK / 'GameplayHud/spr_banner_hud.png', None),
    'status': (DARK / 'Player interface/Player Status/single size player status/spr_player_status_version1.png', None),
    'zslot': (ZELDA / 'Player interface/Player Status/item slots/spr_item_slot_single_charge_zeldalike.png', (0, 0, 31, 24)),
    'heart': (ZELDA / 'Player interface/Player Status/spr_player_healthbar.png', (36, 0, 45, 8)),
}
# relic id -> Tiny Dungeons strip. resonance, drum and veil are hand-made and already in ICON_OUT.
RELIC_STRIPS = {
    'boots': 'armor_01_v2_boots', 'stone': 'monster_loot_desert_sand_giant', 'ricochet': 'jewel_sapphire',
    'repulsion': 'ring_02', 'slipstream': 'armor_02_v2_chestplate', 'bloodroot': 'ring_03',
    'echo': 'monster_loot_snow_boar', 'hunter': 'key_hell_chest_big', 'spite': 'food_01',
}

def main():
    UI_OUT.mkdir(parents=True, exist_ok=True)
    ICON_OUT.mkdir(parents=True, exist_ok=True)
    for name, (src, box) in CROPS.items():
        im = Image.open(src).convert('RGBA')
        (im.crop(box) if box else im).save(UI_OUT / f'{name}.png')
    for relic, strip in RELIC_STRIPS.items():
        Image.open(TINY / f'{strip}.png').convert('RGBA').save(ICON_OUT / f'{relic}.png')
    # Pack Sigil uses the static Ninja Adventure stamp, centred in 16x16 and repeated to match the strip format.
    stamp = Image.open(NINJA / 'Other/Stamp.png').convert('RGBA')
    strip = Image.new('RGBA', (256, 16))
    for i in range(16):
        strip.alpha_composite(stamp, (i * 16 + (16 - stamp.width) // 2, (16 - stamp.height) // 2))
    strip.save(ICON_OUT / 'pack.png')
    for relic in ('resonance', 'drum', 'veil'):
        assert (ICON_OUT / f'{relic}.png').exists(), f'missing hand-made icon {relic}.png'
    FX_OUT.mkdir(parents=True, exist_ok=True)
    for src, name in [('fx/spark_04.png', 'spark_04.png'), ('particle/gem_broken_yellow.png', 'gem_broken_yellow.png'), ('particle/rock_gray.png', 'rock_gray.png')]:
        Image.open(VFXMIX / src).convert('RGBA').save(FX_OUT / name)
    manifest = {}
    for key in FX_FROM_JSON:
        j = json.loads((SHEETS / f'{key}.json').read_text())
        manifest[key] = {'src': f'assets/fx/sheets/{j["image"]}', 'fw': j['frame_width'], 'fh': j['frame_height'], 'n': j['frame_count'],
                         'fps': j.get('fps') or 1, 'loop': bool(j.get('loop')), 'ax': j['anchor']['x'], 'ay': j['anchor']['y']}
    for key, (src, fw, fh, n, fps, loop, ax, ay) in FX_EXTRA.items():
        manifest[key] = {'src': src, 'fw': fw, 'fh': fh, 'n': n, 'fps': fps, 'loop': loop, 'ax': ax, 'ay': ay}
    (ROOT / 'survivor-fx-manifest.js').write_text('// Generated by scripts/build-ui-assets.py from assets/fx/sheets/*.json. Do not edit.\nwindow.FX_SHEETS=' + json.dumps(manifest, separators=(',', ':')) + ';\n')
    print('wrote', sorted(p.name for p in UI_OUT.iterdir()), sorted(p.name for p in ICON_OUT.iterdir()))

if __name__ == '__main__':
    main()
