const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless: true});
  try {
    const page = await browser.newPage({viewport: {width: 540, height: 940}});
    const errors = [];
    page.on('pageerror', error => errors.push(String(error)));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await page.addInitScript(() => { window.__vt_pending = true; });
    await page.goto(process.env.GAME_URL || 'http://localhost:5199');
    await page.waitForFunction(() => window.__phaserReady);
    await page.evaluate(() => document.fonts.ready);
    await page.waitForFunction(() => [...document.images].every(image => image.complete));
    await page.waitForTimeout(1000);
    fs.mkdirSync('output/phaser', {recursive: true});
    const read = () => page.evaluate(() => JSON.parse(window.render_game_to_text()));
    const shot = async name => { await page.waitForTimeout(80); await page.locator('#game').screenshot({path: `output/phaser/${name}.png`}); };
    const click = async (x, y) => { const r = await page.locator('#game').boundingBox(); await page.mouse.click(r.x + x * r.width / 540, r.y + y * r.height / 900); };
    assert.equal((await read()).engine.version, '4.2.1');
    assert.equal(await page.locator('canvas').count(), 1);
    await shot('title');
    await click(270, 700); assert.equal((await read()).mode, 'map');
    await shot('map');
    await click(390, 730); assert.equal((await read()).mode, 'upgrades');
    await page.evaluate(() => window.__scollTest.setSave({gold:1000, unlockedStage:10}));
    await shot('upgrades');
    await click(270, 680);
    assert.equal((await page.evaluate(() => window.__scollTest.getSave())).upgrades.power, 1);
    // Exercise zoom, drag suppression, and reset without buying accidentally.
    const beforeDrag = await page.evaluate(() => window.__scollTest.getSave());
    const box = await page.locator('#game').boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height * 0.45);
    await page.mouse.wheel(0, -120);
    await page.mouse.down(); await page.mouse.move(box.x + box.width * 0.65, box.y + box.height * 0.50, {steps:5}); await page.mouse.up();
    assert.deepEqual(await page.evaluate(() => window.__scollTest.getSave()), beforeDrag);
    await shot('upgrades-panned'); await click(460, 205);
    await page.evaluate(() => { window.__scollTest.setMode('bestiary'); });
    await page.evaluate(() => { const a=window.__scollTest; a.setSave({...a.getSave(), essence:{feral:100,bloom:100,arcane:100}}); });
    await click(270, 741);
    await page.evaluate(() => window.advanceTime(3000));
    assert.equal((await read()).essence.feral, 90);
    assert.equal((await read()).activeParty.length, 1);
    const member = (await read()).activeParty[0];
    await page.evaluate(id => window.__scollTest.toggleCreatureInParty(id), member);
    assert.equal((await read()).activeParty.length, 0);
    await page.evaluate(id => window.__scollTest.toggleCreatureInParty(id), member);
    await shot('bestiary');
    await page.evaluate(() => { window.__scollTest.startStage(1); window.advanceTime(1500); });
    await page.evaluate(() => { const a=window.__scollTest; a.setSave({...a.getSave(),upgrades:{power:1,autoTarget:1},autoTargetEnabled:false}); });
    await page.keyboard.press('Space'); assert.equal((await read()).autoTargetEnabled, true);
    await click(484, 60); assert.equal((await read()).autoTargetEnabled, false);
    const combatBox = await page.locator('#game').boundingBox();
    await page.mouse.move(combatBox.x + combatBox.width * 0.8, combatBox.y + combatBox.height * 0.6);
    assert(Math.abs((await read()).combat.aim.x - 432) < 2);
    await shot('combat');
    assert.equal((await read()).mode, 'combat');
    assert((await read()).combat.projectiles.length > 0);
    assert(await page.evaluate(() => window.scrollMonstersGame.scene.getScene('ScrollMonsters').children.list.some(object => object.type === 'Image' && object.visible)), 'native Phaser images render the scene');
    await page.evaluate(() => window.__scollTest.clearCombat());
    assert.equal((await read()).mode, 'result'); await shot('result');
    await click(270, 715); assert.equal((await read()).mode, 'combat');
    // Force a deterministic defeat through real damage and update logic.
    await page.evaluate(() => { window.__scollTest.startStage(10); for(let i=0;i<100;i++) window.__scollTest.spawnEnemy('boss'); window.advanceTime(20000); });
    assert.equal((await read()).mode, 'result'); assert.equal((await read()).result.won, false);
    await shot('defeat');
    for (let stage = 1; stage <= 10; stage++) {
      await page.evaluate(n => { window.__scollTest.startStage(n); window.advanceTime(100); window.__scollTest.clearCombat(); }, stage);
      assert.equal((await read()).result.won, true);
    }
    const save = await page.evaluate(() => window.__scollTest.getSave());
    await page.reload(); await page.waitForFunction(() => window.__phaserReady);
    const loaded = await page.evaluate(() => window.__scollTest.getSave());
    for (const key of ['gold', 'essence', 'upgrades', 'completed', 'unlockedStage', 'activeParty']) assert.deepEqual(loaded[key], save[key]);
    await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(150);
    const rect = await page.locator('#game').boundingBox();
    assert(rect.x >= 0 && rect.y >= 0 && rect.x + rect.width <= 390 && rect.y + rect.height <= 844, JSON.stringify(rect));
    await shot('mobile');
    await click(270, 700); assert.equal((await read()).mode, 'map');
    await page.goto((process.env.GAME_URL || 'http://localhost:5199') + '/upgrade-prototype.html');
    await page.waitForFunction(() => window.__phaserReady);
    assert.equal((await read()).engine.version, '4.2.1');
    // A second page without the virtual clock must advance under Phaser's loop.
    const live = await browser.newPage({viewport:{width:390,height:844},hasTouch:true});
    live.on('pageerror', error => errors.push(String(error)));
    await live.goto(process.env.GAME_URL || 'http://localhost:5199'); await live.waitForFunction(() => window.__phaserReady);
    await live.evaluate(() => window.__scollTest.startStage(1));
    await live.waitForTimeout(350);
    const liveState = await live.evaluate(() => JSON.parse(window.render_game_to_text()));
    assert(liveState.combat.cameraScroll > 0, 'Phaser updates simulation in real time');
    const touchRect = await live.locator('#game').boundingBox();
    await live.touchscreen.tap(touchRect.x+touchRect.width*0.75, touchRect.y+touchRect.height*0.6);
    const touched = await live.evaluate(() => JSON.parse(window.render_game_to_text()));
    assert(Math.abs(touched.combat.aim.x - 405) < 3, 'touch aim follows scaled coordinates');
    await live.locator('#game').screenshot({path:'output/phaser/touch-combat.png'});
    await live.close();
    assert.deepEqual(errors, []);
    console.log('PASS Phaser 4.2.1: native sprites, all screens, gameplay, victory, saves and mobile sizing; no browser errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
