const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=metal']});try{
const page=await browser.newPage({viewport:{width:1100,height:760}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.addInitScript(()=>window.__vt_pending=true);await page.goto('http://localhost:5174/survivors.html?test');await page.waitForFunction(()=>window.__phaserReady);
const damage=await page.evaluate(()=>{const s=__survivorTest.scene,results=[];for(const split of [false,true]){s.start();s.spawnTimer=999;s.catActive=false;s.player.fire=999;s.upgrades.owlPower=2;const e=s.spawn('beast',850,800);e.hp=e.maxHp=100;e.speed=0;e.clock=999;s.shots.push({x:850,y:800,dx:0,dy:0,life:1,source:'owl',split,hits:new Set(),sprite:s.pooled(s.shotPool,'feather',1)});s.tick(1/60);results.push(100-e.hp);}return results;});assert.equal(damage[0],6);assert(Math.abs(damage[1]-1.98)<1e-9);
const shrine=await page.evaluate(()=>{const s=__survivorTest.scene;s.nestDeckOverride=['owl','beast','cat','mouse','mole','bear'];s.start();s.elapsed=90;s.spawnTimer=999;s.catActive=false;s.player.fire=999;s.player.x=s.expedition.shrine.x;s.player.y=s.expedition.shrine.y;s.player.inv=999;const sh=s.expedition.shrine,tiers=[],levels=[];
s.expedition.updateShrine(3);s.player.x=1200;s.expedition.updateShrine(2);const decayed=sh.progress===0;s.player.x=s.expedition.shrine.x;s.mode='paused';s.tick(6);const paused=sh.progress===0;s.mode='playing';
for(let tier=1;tier<=3;tier++){s.expedition.updateShrine(6);const e=s.enemies.find(e=>e.hp>0&&e.shrineTier===tier);tiers.push([e.hp,e.contactDamage,e.speed,e.chargeSpeed]);const count=s.enemies.length;s.expedition.updateShrine(60);if(s.enemies.length!==count)throw Error('duplicate elite');s.hit(e,9999,'player',s.player);s.checkLevel();if(s.mode==='relic')s.relics.skip();levels.push(s.level);s.chooseUpgrade(0);const completed=sh.completed;s.expedition.updateShrine(60);if(sh.completed!==completed||sh.inCombat)throw Error('automatic retrigger');s.player.x=1200;s.expedition.updateShrine(0);s.player.x=s.expedition.shrine.x;}
s.expedition.updateShrine(60);return {decayed,paused,tiers,levels,completed:sh.completed,done:sh.done,active:sh.active,summons:s.run.events.filter(e=>e.type==='shrine_activated').length,rewards:s.run.events.filter(e=>e.type==='shrine_completed').length};});assert(shrine.decayed&&shrine.paused&&shrine.done&&!shrine.active);assert.deepEqual(shrine.tiers,[[60,12,55,280],[140,18,65,320],[300,26,78,360]]);assert.deepEqual(shrine.levels,[2,3,4]);assert.equal(shrine.summons,3);assert.equal(shrine.rewards,3);
const safety=await page.evaluate(()=>{const s=__survivorTest.scene;s.nestDeckOverride=['owl','beast','cat','mouse','mole','bear'];s.start();s.elapsed=90;s.player.x=s.expedition.shrine.x;s.player.y=s.expedition.shrine.y;for(let i=0;i<150;i++)s.spawn('bat',100,100);s.expedition.updateShrine(6);const capped=!s.expedition.shrine.inCombat;s.start();s.elapsed=90;s.player.x=s.expedition.shrine.x;s.player.y=s.expedition.shrine.y;s.catActive=false;s.player.fire=999;s.spawnTimer=999;s.expedition.shrine.completed=2;s.expedition.updateShrine(6);const e=s.enemies.find(e=>e.shrineTier);e.x=s.player.x;e.y=s.player.y;e.clock=999;s.player.inv=0;s.tick(1/60);return {capped,damage:40-s.player.hp};});assert(safety.capped);assert.equal(safety.damage,26);
await page.evaluate(()=>{const s=__survivorTest.scene;s.nestDeckOverride=['owl','beast','cat','mouse','mole','bear'];s.start();s.elapsed=91;s.player.x=s.expedition.shrine.x;s.player.y=s.expedition.shrine.y+40;s.spawnTimer=999;s.player.inv=999;s.expedition.updateShrine(2);s.draw();});await page.waitForTimeout(100);fs.mkdirSync('output/shrine',{recursive:true});await page.screenshot({path:'output/shrine/altar.png'});
await page.evaluate(()=>{const s=__survivorTest.scene;s.nestDeckOverride=['owl','beast','cat','mouse','mole','bear'];s.player.x=450;s.player.y=850;s.encounters.update(0);s.draw();});await page.waitForTimeout(100);await page.screenshot({path:'output/shrine/nest.png'});
const extra=await page.evaluate(()=>{const s=__survivorTest.scene;s.nestDeckOverride=['owl','beast','cat','mouse','mole','bear'];s.start();s.elapsed=120;s.expedition.update(0);const first=s.enemies.filter(e=>e.elite).length;s.expedition.update(0);const repeated=s.enemies.filter(e=>e.elite).length;s.elapsed=210;s.expedition.update(0);return {first,repeated,total:s.enemies.filter(e=>e.elite).length};});assert.deepEqual(extra,{first:1,repeated:1,total:2});assert.deepEqual(errors,[]);console.log('PASS',{damage,shrine,extra});
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
