const assert = require('node:assert/strict');
const {run, offscreenTexts, listControls} = require('./survivor-test-utils.cjs');

run('Forest demo, unlockable starters, evolution, and guardian ending', async page => {
  await page.waitForTimeout(900);
  await page.screenshot({path: 'output/demo-title.png'});
  const controls = (await listControls(page)).map(c => c.label);
  assert(controls.includes('BEGIN'));
  assert(!controls.includes('Desert') && !controls.includes('Woodland'));
  assert(controls.includes('<') && controls.includes('>'));
  const title = await page.evaluate(() => ({faces: __survivorTest.scene.screens.layout.faces, text: __uiTexts().texts.map(t => t.text)}));
  assert.deepEqual(title.faces.map(f => f.id), ['cat','owl','frog','storm','mollusc']);
  assert.deepEqual(title.faces.filter(f => f.known).map(f => f.id), ['cat']);
  assert(!title.text.some(t => t.includes('BREAK DENS')));
  assert.equal(await page.evaluate(() => performance.getEntriesByType('resource').filter(r => r.name.endsWith('.ogg')).length), 0);
  assert.deepEqual(await offscreenTexts(page), []);
  const owl = await page.evaluate(() => {const s=__survivorTest.scene,f=s.screens.layout.faces.find(v=>v.id==='owl'),c=s.game.canvas.getBoundingClientRect();return {x:c.left+(f.x+19)*2*c.width/s.scale.width,y:c.top+(f.y+19)*2*c.height/s.scale.height};});
  await page.mouse.click(owl.x, owl.y);
  assert.deepEqual(await page.evaluate(() => {const s=__survivorTest.scene;return {preview:s.demoPreview,starter:s.starter,hidden:s.screens.layout.faces.find(f=>f.id==='owl').known};}), {preview:'owl',starter:'cat',hidden:false});
  await page.screenshot({path: 'output/demo-unknown-monster.png'});
  const result = await page.evaluate(() => {
    const s = __survivorTest.scene;
    const layouts = [];
    for (const seed of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) {
      s.seed = seed;
      s.resetState();
      layouts.push({seed, dens: s.encounters.nests.map(n => n.type), positions: s.encounters.nests.map(n => [n.x, n.y]), activeAt: s.encounters.nests.map(n => n.activeAt)});
    }
    s.chooseStarter('owl');
    const refusedStarter = s.starter;
    const preview = s.demoPreview;
    s.start();
    const initialStarter = s.starter;
    const early = [];
    for (const at of [0, 20, 40, 59.9]) {
      s.elapsed = at;
      early.push(...Array.from({length: 40}, () => s.expedition.enemyType()));
    }
    s.elapsed = 0;
    const bat = s.spawn('bat', s.player.x + 300, s.player.y);
    const opening = {appearance: SurvivorEnemies.identity(bat), spawnInterval: s.expedition.interval()};
    s.elapsed = 59.9;
    const nestBeforeMinute = s.encounters.nests.map(n => s.encounters.targets().includes(n));
    s.elapsed = 60;
    s.encounters.update(0);
    const nestAfterMinute = s.encounters.nests.map(n => s.encounters.targets().includes(n));
    s.start();
    s.expedition.release('mollusc', s.player.x, s.player.y, false, 0);
    const body = s.expedition.captureBody('mollusc');
    body.progress = 2.49;
    s.expedition.capture(body, 'mollusc', .02);
    const options = s.creatures.evolution.preview()?.options.map(o => o.id) || [];
    const merged = s.creatures.evolution.choose('octopus');
    const party = s.expedition.party();
    s.mode = 'title';
    s.draw();
    const revealed = s.screens.layout.faces.find(f => f.id === 'mollusc').known;
    const persisted = Expedition.readDemoUnlocks().includes('mollusc');
    s.chooseStarter('mollusc');
    const selectedStarter = s.starter;
    s.start();
    const retryStarter = s.run.starter;
    const retryParty = s.expedition.party();
    s.player.inv = 999;
    s.spawnTimer = 999;
    s.elapsed = 569.99;
    s.tick(.02);
    const firstBoss = s.encounters.boss;
    const guardian = {appeared: s.encounters.bossAppeared, hp: s.encounters.boss?.hp, mode: s.mode, interval: s.spawnInterval()};
    s.elapsed = 589.99;
    const taperInterval = s.spawnInterval();
    s.elapsed = 599.99;
    s.tick(.02);
    const overtime = {mode: s.mode, seconds: s.elapsed, status: s.run.status, guardianHp: s.encounters.boss.hp};
    s.spawnTimer = 0;
    const spawnedAtTen = s.spawned;
    s.tick(.02);
    const spawnedAfterTen = s.spawned;
    s.elapsed = 1140;
    s.tick(.02);
    const sameGuardian = s.encounters.boss === firstBoss && !s.encounters.finalAppeared;
    s.elapsed = 610;
    s.hit(s.encounters.boss, s.encounters.boss.hp, 'player', s.player);
    s.tick(.02);
    const ending = {mode: s.mode, seconds: s.elapsed, status: s.run.status, duration: s.snapshot().duration, swarm: s.encounters.guardianSwarmStarted};
    return {demo: s.isDemo, field: s.field, layouts, refusedStarter, preview, initialStarter, early, opening, nestBeforeMinute, nestAfterMinute, options, merged, party, revealed, persisted, selectedStarter, retryStarter, retryParty, guardian, taperInterval, overtime, spawnedAtTen, spawnedAfterTen, sameGuardian, ending};
  });
  assert(result.demo);
  assert.equal(result.field, 'woods');
  assert.equal(result.refusedStarter, 'cat');
  assert.equal(result.preview, 'owl');
  assert.equal(result.initialStarter, 'cat');
  assert(result.layouts.every(l => l.dens.every(type => ['cat','owl','frog','storm','mollusc'].includes(type))));
  assert(result.layouts.every(l => l.activeAt.every(at => at === 60)));
  assert(new Set(result.layouts.map(l => l.dens.join(','))).size > 3);
  assert(new Set(result.layouts.map(l => JSON.stringify(l.positions))).size > 3);
  assert.deepEqual([...new Set(result.early)], ['bat']);
  assert(['golem','forestGolem','energyGolem'].includes(result.opening.appearance));
  assert.equal(result.opening.spawnInterval, .85);
  assert(result.nestBeforeMinute.every(v => !v));
  assert(result.nestAfterMinute.every(Boolean));
  assert(result.options.includes('octopus'));
  assert(result.merged);
  assert.deepEqual(result.party, ['octopus']);
  assert(result.revealed);
  assert(result.persisted);
  assert.equal(result.selectedStarter, 'mollusc');
  assert.equal(result.retryStarter, 'mollusc');
  assert.deepEqual(result.retryParty, ['mollusc']);
  assert(result.guardian.appeared);
  assert.equal(result.guardian.mode, 'playing');
  assert(result.taperInterval > result.guardian.interval);
  assert.equal(result.overtime.mode, 'playing');
  assert(result.overtime.seconds >= 600);
  assert.equal(result.overtime.status, 'in_progress');
  assert.equal(result.spawnedAfterTen, result.spawnedAtTen);
  assert(result.sameGuardian);
  assert.equal(result.ending.duration, 600);
  assert.equal(result.ending.mode, 'won');
  assert(result.ending.seconds >= 600);
  assert.equal(result.ending.status, 'won');
  assert.equal(result.ending.swarm, false);
  await page.waitForFunction(() => __survivorTest.scene.cache.audio.exists(`music:${window.GAME_MUSIC.combat.length}`), null, {timeout: 15000});
  await page.screenshot({path: 'output/demo-ending.png'});
  assert.deepEqual(await offscreenTexts(page), []);
  await page.evaluate(() => {const s=__survivorTest.scene;s.start();s.tick(1);s.draw();});
  await page.screenshot({path: 'output/demo-gameplay.png'});
  await page.reload();
  await page.waitForFunction(() => window.__phaserReady);
  await page.waitForTimeout(900);
  const mollusc = await page.evaluate(() => {const s=__survivorTest.scene,f=s.screens.layout.faces.find(v=>v.id==='mollusc'),c=s.game.canvas.getBoundingClientRect();return {known:f.known,x:c.left+(f.x+19)*2*c.width/s.scale.width,y:c.top+(f.y+19)*2*c.height/s.scale.height};});
  assert(mollusc.known);
  await page.mouse.click(mollusc.x, mollusc.y);
  await page.waitForTimeout(450);
  await page.screenshot({path: 'output/demo-unlocked-title.png'});
  const begin = (await listControls(page)).find(c => c.label === 'BEGIN');
  await page.mouse.click(begin.x, begin.y);
  const savedRetry = await page.evaluate(() => {const s=__survivorTest.scene;return {known:s.unlocked.includes('mollusc'),starter:s.run.starter,party:s.expedition.party()};});
  assert.deepEqual(savedRetry, {known:true,starter:'mollusc',party:['mollusc']});
}, 'demo.html?field=desert&test').catch(error => {console.error(error); process.exitCode = 1;});
